type: section
icon: search
fields:
  metaTitle:
    label: Seitentitel
    type: text
    width: 1/2
  metaDescription:
    label: Seitenbeschreibung
    type: textarea
    buttons: false
    help: &pi; × 👍 eine SMS-Länge (160 Zeichen). Wird auf der Google Suchergebnisseite ausgegeben.
  ogImage:
    label: Open Graph Image
    type: files
    files: images
    multiple: false
    help: Vorschaubild für Soziale Netzwerke
  robots:
    label: Robots
    type: select
    width: 1/2
    options:
      - 'index,nofollow'
      - 'noindex,follow'
      - 'noindex,nofollow'
    placeholder: 'index,follow (Standard)'
    help: Anweisungen für Suchmaschinen-Crawler zur Indexierung der Inhalte
