type: section
icon: search
label: seo-tab-label
fields:
  metaTitle:
    label: seo-tab-meta-title
    type: text
    width: 1/2
  metaDescription:
    label: seo-tab-meta-description
    type: textarea
    buttons: false
    help: seo-tab-meta-description-help
  ogImage:
    label: seo-tab-og-image
    type: files
    files: images
    multiple: false
    help: seo-tab-og-image-help
  robots:
    label: seo-tab-robots
    type: select
    width: 1/2
    options:
      - 'index,nofollow'
      - 'noindex,follow'
      - 'noindex,nofollow'
    placeholder: 'index,follow (Standard)'
    help: seo-tab-robots-help
